[package]
name = "pacy-egui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pacy = { path = "../pacy" }
egui = "0.18"
